### ISSUE TITLE
Possible OOM

### ISSUE THREAD

**Issue by dmitryvvv** [olofhagsand/cligen#13]
> size_t diff;

On some platforms `size_t `type may be defined as:

> typedef undefined int size_t 

and block which allocates memory may not happen.

`cbuf_append` function in `cligen_buf.c`

**Comment by olofhagsand** [comment]
Thanks. fixed.

**Comment by vdv18** [comment]
Cool. Thanks.

**Comment by dmitryvvv** [comment]
Cool. Thanks.
