### ISSUE TITLE
request: move some structs to a private header file

### ISSUE THREAD

**Issue by dcornejo** [olofhagsand/cligen#15]
Request that you move some of the structures which are not publicly exposed - cbuf, and cvec come to mind - to separate private header files which are not installed.

in our use case, we have added functions that are not of general interest and rather than maintain them as diffs to the cligen core, we could simply create a new file and avoid conflicts and errors.

**Comment by olofhagsand** [comment]
Four new internal headers created: cligen_cv_internal.h, cligen_cvec_internal.h, cligen_buf_internal.h and cligen_handle_internal.h
