### ISSUE TITLE
change to cligen_config.h.in

### ISSUE THREAD

**Issue by dcornejo** [olofhagsand/cligen#17]
On certain compilers I get an warning that says that cligen_custom.h should be in quote rather than angle brackets since it is in the compilation directory. Attached is a very small patch to fix this.

[patch_cligen_config.h.in.txt](https://github.com/olofhagsand/cligen/files/2410004/patch_cligen_config.h.in.txt)

**Comment by olofhagsand** [comment]
thanks!

**Comment by olofhagsand** [comment]
@dcornejo I gett his again when I run autoheader that generates cligen_config.h.in.  Just have to remember to make the manual patch after each run of autoheader.
