### ISSUE TITLE
serial terminals line wrap at 21 characters

### ISSUE THREAD

**Issue by dcornejo** [olofhagsand/cligen#20]
When accessing the CLI using a serial port, the content wraps before the edge of the screen:

```
localhost.localdomain tnsr(config)# auth u
ser dsfjlkdsadfmdslkf
fhtosprjdemsofjtneyfq
```

where this was typed as a single line. notice that it wraps after 21 characters on the second and succeeding lines.

this does not happen when accessing the CLI via ssh.

the problem seems to be in cligen_handle.c:cligen_gwinsz() - a serial console seems to report a screen dimension of 0 x 0. in cligen_handle.c:cligen_terminal_length_set() any line length is set to a minimum of 21 characters.

in the case where the terminal dimensions are not available (0 x 0), it should disable all the special scrolling behavior and allow the terminal to deal with over length lines. or something like that.

**Comment by olofhagsand** [comment]
Should be fixed now: If no terminal (eg serial) set the terminal width to a large number effectively disabling scrolling behaviour.
