### ISSUE TITLE
Choice with space is not working in CLIgen code:

### ISSUE THREAD

**Issue by ashuagarwal01** [olofhagsand/cligen#24]
Choice with a space is not parsed by Cligen code.

Example:

1.	choice  ("Choice example") <string choice:unknown|NoSpace|with\ space>, fn_cb();    -->not working
2.	choice  ("Choice example") <string choice:unknown|NoSpace|”with space”>, fn_cb();    -->not working

As per yang RFC, space is a valid character in choice type. 

Please note: Auto-complete work for first case, but when you press enter, it will say invalid token.

**Comment by olofhagsand** [comment]
Yes. Space is not allowed in CLIgen choice type.
I would like to understand the use-case better (to be able to come up with a solution):
- In what example do you need identifiers with space?
- Do you use generated Yang/CLIgen code?
- If so, Yang choice is different from CLIgen choice, Yang enumeration and some others are generated into CLIgen choice, but not Yang choice (which is generated into {case1; case2;} )

**Comment by ashuagarwal01** [comment]
Yang Enumeration is considered as choice in  Cligen as per my understanding. 
https://tools.ietf.org/html/rfc6020#section-9.6.4 explain that space is valid keyword in enum. 

I am taking an example of Clixon. I modified example.yang in clixon as below:

    /* Translation function example - See also example_cli */
    list translate{
        leaf value{
            type uint32 {
              range "2..max";
            }
        }
        leaf port {
          type enumeration
          {
            enum unknown;
            enum without-space;
            enum "with space";
          }
        }
    }

The clixon_cli  parse this yang as :

translate{
      value (<value:uint32 range[2:4294967295]>|<value:uint32 expand_dbvar("candidate","/translate/value")>),overwrite_me("/translate/value");
      **port <port:string choice:unknown|without-space|with space>**,overwrite_me("/translate/port");
   }


Which is incorrect and failing the clixon_cli parsing.

**Comment by olofhagsand** [comment]
This should now work using backslash escape code, eg:
`choice with\ space`
please verify

**Comment by ashuagarwal01** [comment]
Patch is working as expected.
Thanks for the fix.

**Comment by olofhagsand** [comment]
thanks
