### ISSUE TITLE
Cligen history doesn't work well with multi line commands

### ISSUE THREAD

**Issue by sharmadeepak29** [olofhagsand/cligen#26]
To reproduce the issue follow below steps:-

set gl_scrolling_mode to 0 in cligen to enable multiline commands.
now type type a command such that it fits in a single line.(eg: aa bb cc)
Then type a command which spans across multiple lines.(eg: any command that occupies atleast 2 lines on the cli terminal)

Then use the up arrow key twice and you will see data is no longer legible.

**Comment by olofhagsand** [comment]
Should work now. Please verify.

**Comment by sharmadeepak29** [comment]
Thanks, it's working now.
