### ISSUE TITLE
How to use auth option? 

### ISSUE THREAD

**Issue by sidbav** [olofhagsand/cligen#30]
If I have a syntax such as:
```
aa { 
  bb, auth="show", cb();
  cc { 
    dd, auth="super", cb();
  }
  ee, cb();
} 
```
How exactly is it enforced that someone with super/show or any authorization can run certain commands?

**Comment by olofhagsand** [comment]
The auth keyword is not supported in cligen itself. It has been implemented in applications using cligen. Such as rost. In clixon authorization is made by NACM (RFC 8341).
I have personally no plans to implement it at the cligen level.

**Comment by olofhagsand** [comment]
Thanks for detecting it. Will be removed from the tutorial.
