### ISSUE TITLE
Is it possible to hide non-terminal commands?

### ISSUE THREAD

**Issue by sidbav** [olofhagsand/cligen#31]
Lets say I have the following syntax
```
aa {
  bb, hide {
     cc, cb();
  }
}
```

Right now you are unable to hide the command aa bb (you are able to tab it).

**Comment by olofhagsand** [comment]
Confirmed. hide only works for terminals. It would be nice to work also for non-terminals.

**Comment by sidbav** [comment]
Do you know when a fix for this would be available?

**Comment by olofhagsand** [comment]
I have not scheduled this. I can have a look at it, maybe next week, it is probably minor.

**Comment by olofhagsand** [comment]
It should be fixed now, please verify

**Comment by sidbav** [comment]
Yes it it working now! Thanks for making the fix so quickly!
