### ISSUE TITLE
Syntax to enter commands regardless of order

### ISSUE THREAD

**Issue by sidbav** [olofhagsand/cligen#32]
Is there a syntax to specify a valid command regardless of the order the command is entered? 

For example, I want the following commands to be valid:
```
cli> aa bb cc dd
cli> aa bb dd cc
cli> aa cc bb dd
cli> aa cc dd bb
cli> aa dd cc bb
cli> aa dd bb cc
```

Right now I believe you would have to explicitly state each command in the syntax like so:
```
aa { 
  bb { 
    cc dd;
    dd cc;
  }
  cc { 
    bb dd;
    dd bb;
  }
  dd { 
    bb cc;
    cc bb;
  }
}
```

It is fine implementing this when there are only a few commands which you want like this. (i.e here we have 3 keyword, so only 3! (6) to consider)

However, if you have lots of commands like this. then the amount of permutations that you need to consider grows quickly! 

Any solution to this?

**Comment by olofhagsand** [comment]
See https://github.com/olofhagsand/cligen/issues/22 (and https://github.com/olofhagsand/cligen/issues/23). 
This is a sufficiently common request so I will try to look into it.

**Comment by olofhagsand** [comment]
New "sets" feature added, see:
https://github.com/olofhagsand/cligen/commit/ed1997a0c335f49073d287a2469a28d39540e791

Example: aa @{ bb; cc; dd; }

**Comment by sidbav** [comment]
Great! This seems to be working! Thanks for adding it in!
