### ISSUE TITLE
Ability to use show attribute to display a multiword string

### ISSUE THREAD

**Issue by sidbav** [olofhagsand/cligen#33]
I want to be able to display a multiword string when hitting tab using the show attribute. I have tried to use the following syntax:
```
aa<int32 show:"A number">
```
But I get an error stating complaining about the "

When I try to use the following
```
aa<int32 show:A\ number>
```

When I tab it see the following:

```
cli> aa 
<A\ number>
```

Any way to use show so that I see the following:
```
cli> aa 
<A number>
```

**Comment by olofhagsand** [comment]
You can do this:
```
aa<a:int32 show:number>("A number");
```
which gives:
```
cli> aa ?
  <number>              A number
```
But if I understand you correctly you want to have:
cli> aa ?
  <a number>            A number
```
Is that correct?

**Comment by sidbav** [comment]
No I would like to have the option to use show so that I can display a multi word string when I tab. 

So for example if I have the following syntax. 
```
aa<aa:int32 show:"A number">("some help description");
```

So that when a user hits tab they see the following:
```
cli> aa (User hits TAB) 
  <A number>
```

Then why I do ? I would see the following:
```
cli> aa ? 
  <A number>            some help description
```

Would something like this be possible?

**Comment by olofhagsand** [comment]
Added fix, please verify.

**Comment by sidbav** [comment]
Yes it is working as expected, thanks!
