### ISSUE TITLE
is decimal 64 broken? 

### ISSUE THREAD

**Issue by sidbav** [olofhagsand/cligen#35]
Does not seem to be working regardless of if you provide fraction digits, (always set to 0 for whatever reason).

**Comment by sidbav** [comment]
Also the syntax given in the tutorial is incorrect for fraction-digits. 

In the tutorial it is:
fraction-digits 4

Whereas it should be 
fraction-digits:4

**Comment by olofhagsand** [comment]
try eg ` <d:decimal64 fraction-digits:4>;` 
how does it not work?
Yes, typo in tutorial, thanks.

**Comment by sidbav** [comment]
So I used the following syntax: 
```
d<d:decimal64 fraction-digits:4>;
```

Then when I am entering a command I see the following:
```
cli> d 2.2 cv parse error: parse_dec64: fraction-digit=0 given but should be in interval [1:18]
```

**Comment by olofhagsand** [comment]
Cannot recreate.
For debugging, please add -d in Makefile as follows:
```
197c197
<       $(LEX) -Pcligen_parse cligen_parse.l # -d is debug 
---
>       $(LEX) -d -Pcligen_parse cligen_parse.l # -d is debug 
```
and log output here.

**Comment by sidbav** [comment]
```
--accepting rule at line 122 ("d")
--accepting rule at line 111 ("<")
--accepting rule at line 142 ("d")
--accepting rule at line 140 (":")
--accepting rule at line 142 ("decimal64")
--accepting rule at line 141 (" ")
--accepting rule at line 161 ("fraction-digits")
--accepting rule at line 149 (":")
--accepting rule at line 167 ("2")
--accepting rule at line 148 (">")
--accepting rule at line 109 (";")
--(end of buffer or a NUL)
--EOF (start condition 0)
```

**Comment by sidbav** [comment]
I have found the problem. 

In cligen_match.c, the function add_cov_to_cvec, the following code needed to be added in: 

```
if (co->co_vtype == CGV_DEC64) /* XXX: Seems misplaced? / too specific */
		cv_dec64_n_set(cv, co->co_dec64_n);
```

**Comment by olofhagsand** [comment]
I still cannot recreate it. Do you have other commands in your cligen spec file? 
If so, either log them here, or try to remove them until you find a minimal set of commands that causes the failure.

**Comment by sidbav** [comment]
No the only command I have is 
```
d<d:decimal64 fraction-digits:4>;
```

I cloned this repo again, and was still facing this issue. 
Have you tried to run with a clean build? If not maybe try to build everything from scratch and try again to see if you face this issue?

**Comment by olofhagsand** [comment]
Yes, now I got it, it is not the parsing or command evaluation (ie <cr>), it occurs in query or completion, ie <tab> or '?'. It was not clear to me.

**Comment by sidbav** [comment]
Yes that is correct is occurs when I hit tab. I should have made that more clear.

**Comment by sidbav** [comment]
I am going to close this issue, since you have merged the PR
