### ISSUE TITLE
Ability to hide an option when using Choice

### ISSUE THREAD

**Issue by sidbav** [olofhagsand/cligen#37]
So I have the following syntax: 
```
aa<aa:string choice:bb|cc|dd|ee>;
```

Is there a way for me to hide an option (for example dd) when the user hits tab?

**Comment by olofhagsand** [comment]
You should be able to do like this:
```
  aa {
    <aa:string choice:bb|cc|ee>;
    <aa:string choice:dd>,hide;
  }
```

**Comment by sidbav** [comment]
yeah that seems to be working, thanks!

**Comment by sidbav** [comment]
If there is a subtree that follows this variable, how exactly would that be implemented?

For example I have the command aa ff. How would it so that I can I hide the choices I would like, and have a subtree following it?

**Comment by olofhagsand** [comment]
I think you need to replicate the tree, or use the `@subtree` syntax.

**Comment by sidbav** [comment]
okay thanks!
