### ISSUE TITLE
Option to Enter Command Without Variables

### ISSUE THREAD

**Issue by owenlejeune** [olofhagsand/cligen#40]
Given the `.cli` syntax
```
aa<aa-var:string>), cb();
```
I would like to be able to type the command `aa` without a variable, as well as `aa <variable>`.  Is the possible to achieve currently?

**Comment by olofhagsand** [comment]
Yes, in several ways:
```
aa, cb(); {
   <aa-var:string>, cb();
}
```
or 
```
aa [<aa-var:string>], cb();
```

**Comment by owenlejeune** [comment]
Perfect, that works! Thanks!
