### ISSUE TITLE
Vararg Variables for Terminal Commands

### ISSUE THREAD

**Issue by owenlejeune** [olofhagsand/cligen#41]
For a terminal command with variable, I would love the ability to enter multiple values for the variable.  For example, implementing the bash command `ls` with the cli format
```ls("list files")[<ls-var:string>], cb();``` 
I would like to be able to enter commands with multiple variables (eg. `ls -l -a`, `ls -a dirname`, etc.) without having to enter the variables in quotes (`ls "-l -a"`) to simulate typical bash syntax.  Is this something that would be feasible? I looked into using sets for this but it doesn't seem to fit this use case

**Comment by olofhagsand** [comment]
You can use `<ls-var:rest>` which means you get the whole rest-of-line in one variable string. It is not "varargs" in the sense that you get separate variables for each space-separated token. So you need to parse that single variable yourself to extract the "-l" or "-a".
Maybe you could use sets, if you do something like `ls @{-a; -l;}` but you currently cannot do it more advanced, such as `ls @{-a [<dirname>]; -l;}`

**Comment by owenlejeune** [comment]
This is actually an even better solution for my use case than varargs!  For my implementation I have to build the args into a string anyway so using `rest` seems to work perfectly.
