### ISSUE TITLE
Command not recognized when it has 'expand' syntax is used

### ISSUE THREAD

**Issue by bbergquist0930** [olofhagsand/cligen#44]
This is from the last code on master pulled today 2019-03-19
```
brett@brett-Precision-7740:~/git/cligen$ ./cligen_tutorial -f tutorial.cli 
Syntax:
aa bb, cb();{
      ca("help ca") <int32:int32>, letters();{
            dd, letters();
            ee, letters();
         }
      cb("help cb"), letters();{
         dd, letters();
         ee, letters();
      }
      ff, cb();
   }
access-list("ACL") permit("permit") <src:ipv4addr show:"A.B.C.D">("Source address") <dst:ipv4addr show:"A.B.C.D">("Destination address");
add @sub, add();
change{
   prompt <new:string>("New prompt"), setprompt();
   tree, changetree(0 : (null) = tree1
);
}
del @sub, del();
ex <a:int32 show:"number">("A number");
hello("Greet the world") world, hello(0 : (null) = Hello World!
);
increment <var:string translate:incstr()>, cb();
interface <ifname:string interface("")>("interface name"), cb();
ip("The IP protocol"){
   tcp("The TCP protocol") <port:int32>("Port number"), cb(0 : (null) = tcp
);
   udp("The UDP protocol") <addr:ipv4addr>("IPv4 address"), cb(0 : (null) = udp
);
}
quit("quit the CLI"), quit();
recurse @tutorial;
secret, hide, secret(0 : (null) = message
);
values{
   aa, cb();
   <int32:int32>, cb();
   <int64:int64>, cb();
   <string:string>, cb();
}
Syntax:
x y, fn(0 : (null) = a
);
Syntax:
change tree, changetree(0 : (null) = tutorial
);
z x;
cli> interface eth0
CLI syntax error in: "interface eth0": Unknown command
cli> 
```
The `interface` function is being called to provide the list of options, but then the command is not recognized nor is the callback function `cb` called.

**Comment by bbergquist0930** [comment]
Maybe the issue is in here ```
int 
cliread_parse(cligen_handle h, 
	      char         *string,
	      parse_tree   *pt,     /* Orig */
	      cg_obj      **co_orig,
	      cvec         *cvv)
{
    int           retval = -1;
    cg_obj       *match_obj;
    parse_tree    ptn={0,};     /* Expanded */
    cvec         *cvec = NULL;

    if (cligen_logsyntax(h) > 0){
	fprintf(stderr, "%s:\n", __FUNCTION__);
	pt_print(stderr, *pt, 0);
    }
    cli_trim(&string, cligen_comment(h));
    if (pt_expand_treeref(h, NULL, pt) < 0) /* sub-tree expansion, ie @ */
	goto done; 
    if ((cvec = cvec_start(string)) == NULL)
	goto done;
    if (pt_expand_2(h, pt, cvec, 0, 0, &ptn) < 0)      /* expansion */
	goto done;
    if ((retval = match_pattern_exact(h, string, ptn, 1, 0, /* XXX cliread_parse */
				      cvec, &match_obj)) < 0)
	goto done;
```
The call to 'match_pattern_exact' is being called with `0` for the `expandvar` parameter.  If I change this to `1`, then the issue goes away.  Maybe the matcher need to have the 'expand' function called so that the command line entered can match with the actual parameter against the list provided?

**Comment by olofhagsand** [comment]
Thanks for pointing this out. It was an experiment to try to limit the calls to expand/completion that could be heavy for large lists. It may be that it is enough to flip the expandvar flag as you indicate ^ but for now I revert the whole patch.
