### ISSUE TITLE
cligen parse abnormal 

### ISSUE THREAD

**Issue by yshchm** [olofhagsand/cligen#5]
Hi olofhagsand:

   I used latest cligen code(2018-01-27 7925db3be)with following cli file,
   
   	snmp set <$cfg_type%g:string choice:sysname> ,cb();     
                                                        
   	snmp <$test:string choice:hello>,cb();                  
   	snmp set <$priv_cfg_type%g:string choice:priv> ,cb();   
                                                        
   	snmp set <$access_cfg_type%g:string choice:access>,cb();

**Comment by yshchm** [comment]
Hi olofhagsand:
      Current  abnormal result:

    cli> snmp set priv
     CLI syntax error in: "snmp set priv": Unknown command

**Comment by olofhagsand** [comment]
Yes, this is a limitation. I will look into if possible to remedy.
As a workaround you can put the three choice options in a single clause:
<var:string choice:sysname|priv|access>

**Comment by yshchm** [comment]
Thanks for your reply.
Yesterday's configuration was a simplified model,The current real configuration is as follows.

   	snmp set <$cfg_type%g:string choice:sysname|syscontact|syslocation|rocommunity|rwcommunity> <$val:string> ,cb("$cfg_type","$val");
   	snmp <$operation%g:string choice:start|restart|stop> ,cb("$operation");                  
   	snmp set <$priv_cfg_type%g:string choice:priv> <$type:string choice:des|aes> ,cb("$priv_cfg_type","$type"); 
   	snmp set <$access_cfg_type%g:string choice:access> <$type:string choice:noauth|auth|priv>,cb("$access_cfg_type","$type");
   	
The cligen parser will become normal if I adjust the configuration to following.

   	snmp set <$cfg_type%g:string choice:sysname|syscontact|syslocation|rocommunity|rwcommunity> <$val:string> ,cb("$cfg_type","$val");
   	snmp set <$priv_cfg_type%g:string choice:priv> <$type:string choice:des|aes> ,cb("$priv_cfg_type","$type"); 
   	snmp set <$access_cfg_type%g:string choice:access> <$type:string choice:noauth|auth|priv>,cb("$access_cfg_type","$type");   	  	
   	snmp <$operation%g:string choice:start|restart|stop> ,cb("$operation");  
   	
I also try the latest release version 3.5.0(2014-12-30 a4c7062),it parses the first configuration normally.

Looking forward to your update.

**Comment by olofhagsand** [comment]
Hello,
I have looked into it. I dont think it worked in 3.5.0, are you sure? As far as I see, it does not work in 3.5.0 or 3.6.0 either. I dont think it ever worked.
CLIgen assumes some ordering of the commands, at least on the levels of similar variables (as in this case). 
It is possible to change so that it can merge variables also not adjacent as in this example, but it needs some medium-scale rewrite.
For now, can you please work-around by sorting variables that need merging so that they are adjacent?
I will add this in the TODO.

**Comment by olofhagsand** [comment]
Looking deeper. Fixed by https://github.com/olofhagsand/cligen/commit/0f49462598ce8fe46699e93a917143db9acd4a68
Thanks for detecting this. Please verify

**Comment by yshchm** [comment]
Thank you for your patch.
I have verified that the problem has been fixed after patching.
